# Generated by Django 3.0.3 on 2020-02-19 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='card number')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('expiration_date', models.DateField(verbose_name='expiration date')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name')),
                ('cvv', models.CharField(max_length=4)),
                ('limit', models.FloatField(verbose_name='limit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
