# Generated by Django 3.0.3 on 2020-02-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='wallets.Wallet'),
        ),
        migrations.AlterField(
            model_name='card',
            name='limit',
            field=models.FloatField(default=0.0, verbose_name='limit'),
        ),
        migrations.AlterModelTable(
            name='card',
            table='cards',
        ),
    ]
