# Generated by Django 3.0.3 on 2020-02-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200219_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='available_credit',
            field=models.FloatField(default=0.0, verbose_name='available credit'),
        ),
    ]
