# Generated by Django 3.0.3 on 2020-02-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'wallet', 'verbose_name_plural': 'wallets'},
        ),
    ]
